# Generated by Django 5.2.1 on 2025-07-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('free', '자유'), ('diary', '일기'), ('activity', '활동')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
