# Generated by Django 5.2.1 on 2025-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('diary', '일기'), ('activity', '활동'), ('2d', '2D'), ('3d', '3D'), ('android-permission', 'Android Permission'), ('chatbot', 'Chatbot'), ('classification', 'Classification'), ('flea-market', 'Flea Market'), ('green-code', 'Green Code')], default='free', max_length=20),
        ),
    ]
