# Generated by Django 5.2.1 on 2025-07-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('tag1', 'tag1'), ('tag2', 'tag2'), ('tag3', 'tag3')], default='tag1', max_length=20),
        ),
    ]
